### ISSUE TITLE
Which search engine should we use?

### ISSUE THREAD

**Issue by TimvdLippe** [MoodCat/MoodCat.me#23]
If we want to make searching possible through our indexed database, which search engine should we use?

Some possibilities:
- plain SQL queries using Hibernate
- [Hibernate search engine](http://hibernate.org/search/) requires additional setup and learning, but has higher performance
- [Elastic Search](https://www.elastic.co/) standard search engine, like Hibernate

**Comment by GijsWeterings** [comment]
I would like to use elasticsearch for the experience, as well as the Nice feature of near instant results. I do feel this is a matter to be death with at a late stage in the project, as it is purely nice to have. Worst case we don't have time and users have to search a list.

While typing I vaguealy remember sound cloud having an api endpoint for search as well. We'll have to set up some requirements of what we want to search when we get to it

**Comment by jwgmeligmeyling** [comment]
I also would like to use Elasticsearch for the experience. SQL is slow for text search (and bad in proper result ordering), however, for our case it might be enough. Maybe we don't even need text search because we can use search api's. The benefit for using Hibernate Search over Elasticsearch would be that it maps to our existing entities and database, and does not require to create Elasticsearch instances and insert all data into Elastic aswell. So the setup would be significantly less. (If we ever get at this point but need to implement it fast). Both are Lucene/Solr based.
